module.exports = {
    APP_STARTUP:"APP-STARTUP",
    UI_READY:"USER-INTERFACE-READY",
    OPEN_DIR_PROMPT:"OPEN-DIRECTORY-PROMPT",
    UI_MODE_TOGGLE:"USER-INTERFACE-MODE-TOGGLE",
    OPEN_FILE:"OPEN-FILE",
    SAVE_FILE:"SAVE-FILE",
    RUN_GUI:"RUN-GUI",
    STOP_GUI:"STOP-GUI",
    UPDATE_GUI:"UPDATE_GUI",
    PROJECT_TYPE:"PROJECT_TYPE",
    PROJECT_DEP:"PROJECT-DEPENDENCIES",
    NEW_FILE:"NEW-FILE",
    NEW_FOLDER:"NEW-FOLDER",
    DIR_PRESENT:"DIR-PRESENT",

}